name: Dev

on:
  push:
    branches: [ "devs" ]
  pull_request:
    branches: [ "devs" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: hola
      run: echo hola

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y build-essential debhelper
        sudo apt install -y libacl1-dev libudev-dev libnotify-dev
    
    - name: Build DEB package
      run: sudo scripts/package.sh # this builds the .deb package

  release:
  
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/devs'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
  
      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
  
      - name: Get date and SHA
        id: vars
        run: |
          echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
          echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
  
      - name: Create tag
        id: create_tag
        run: |
          TAG="v${{ env.DATE }}-${{ env.SHA }}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          git tag "$TAG"
          git push origin "$TAG"
  
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: "Dev release ${{ env.TAG }}"
          files: ../balrog_build/*.deb
          body: |
            Autogenerated dev release
            - Commit ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
